return (require"lib.codec")(function()

map {"Type", type=t_U8, register=true, values={
  {"nodata",    0x00, 0xFF},
  {"data8",     0x08, 0xFF},
  {"data16",    0x09, 0xFF},
  {"data24",    0x0a, 0xFF},
  {"data32",    0x0b, 0xFF},
  {"data40",    0x0c, 0xFF},
  {"data48",    0x0d, 0xFF},
  {"data56",    0x0e, 0xFF},
  {"data64",    0x0f, 0xFF},
  {"bool",      0x10, 0xFF},
  {"map8",      0x18, 0xFF},
  {"map16",     0x19, 0xFF},
  {"map24",     0x1a, 0xFF},
  {"map32",     0x1b, 0xFF},
  {"map40",     0x1c, 0xFF},
  {"map48",     0x1d, 0xFF},
  {"map56",     0x1e, 0xFF},
  {"map64",     0x1f, 0xFF},
  {"uint8",     0x20, 0xFF},
  {"uint16",    0x21, 0xFF},
  {"uint24",    0x22, 0xFF},
  {"uint32",    0x23, 0xFF},
  {"uint40",    0x24, 0xFF},
  {"uint48",    0x25, 0xFF},
  {"uint56",    0x26, 0xFF},
  {"uint64",    0x27, 0xFF},
  {"int8",      0x28, 0xFF},
  {"int16",     0x29, 0xFF},
  {"int24",     0x2a, 0xFF},
  {"int32",     0x2b, 0xFF},
  {"int40",     0x2c, 0xFF},
  {"int48",     0x2d, 0xFF},
  {"int56",     0x2e, 0xFF},
  {"int64",     0x2f, 0xFF},
  {"enum8",     0x30, 0xFF},
  {"enum16",    0x31, 0xFF},
  {"semi",      0x38, 0xFF},
  {"single",    0x39, 0xFF},
  {"double",    0x3a, 0xFF},
  {"octstr",    0x41, 0xFF},
  {"string",    0x42, 0xFF},
  {"octstr16",  0x43, 0xFF},
  {"string16",  0x44, 0xFF},
  {"array",     0x48, 0xFF},
  {"struct",    0x4c, 0xFF},
  {"set",       0x50, 0xFF},
  {"bag",       0x51, 0xFF},
  {"ToD",       0xe0, 0xFF},
  {"date",      0xe1, 0xFF},
  {"UTC",       0xe2, 0xFF},
  {"clusterId", 0xe8, 0xFF},
  {"attribId",  0xe9, 0xFF},
  {"bacOID",    0xea, 0xFF},
  {"EUI64",     0xf0, 0xFF},
  {"key128",    0xf1, 0xFF},
  {"unk",       0xff, 0xFF}
}}

local function iftype(t, ...) return opt{nil, when=function(v) return v.Type==t end, ...} end
msg{"Attribute",
  map {ref="Type"},
  iftype("data8", arr{"Value", type=t_U8, length=1}),
  iftype("data16", arr{"Value", type=t_U8, length=2}),
  iftype("data24", arr{"Value", type=t_U8, length=3}),
  iftype("data32", arr{"Value", type=t_U8, length=4}),
  iftype("data40", arr{"Value", type=t_U8, length=5}),
  iftype("data48", arr{"Value", type=t_U8, length=6}),
  iftype("data56", arr{"Value", type=t_U8, length=7}),
  iftype("data64", arr{"Value", type=t_U8, length=8}),
  iftype("bool", bool{"Value"}),
  iftype("map8", bmap{"Value", bytes=1}),
  iftype("map16", bmap{"Value", bytes=2}),
  iftype("map24", bmap{"Value", bytes=3}),
  iftype("map32", bmap{"Value", bytes=4}),
  iftype("map40", bmap{"Value", bytes=5}),
  iftype("map48", bmap{"Value", bytes=6}),
  iftype("map56", bmap{"Value", bytes=7}),
  iftype("map64", bmap{"Value", bytes=8}),
  iftype("uint8", U8{"Value"}),
  iftype("uint16", U16{"Value"}),
  iftype("uint24", U24{"Value"}),
  iftype("uint32", U32{"Value"}),
  iftype("uint40", U40{"Value"}),
  iftype("uint48", U48{"Value"}),
  iftype("uint56", U56{"Value"}),
  iftype("uint64", U64{"Value"}),
  iftype("int8", I8{"Value"}),
  iftype("int16", I16{"Value"}),
  iftype("int24", I24{"Value"}),
  iftype("int32", I32{"Value"}),
  iftype("int40", I40{"Value"}),
  iftype("int48", I48{"Value"}),
  iftype("int56", I56{"Value"}),
  iftype("int64", I64{"Value"}),
  iftype("enum8", U8{"Value"}),
  iftype("enum16", U16{"Value"}),
  iftype("semi", U16{"Value", const=0xFFFF}), -- not yet implemented!
  iftype("single", float{"Value"}),
  iftype("double", double{"Value"}),
  iftype("octstr", arr{"Value", asstring=true, type=t_U8, counter=t_U8}),
  iftype("string", arr{"Value", asstring=true, type=t_U8, counter=t_U8}),
  iftype("octstr16", arr{"Value", asstring=true, type=t_U8, counter=t_U16}),
  iftype("string16", arr{"Value", asstring=true, type=t_U8, counter=t_U16}),
  iftype("array", nil), -- not yet implemented
  iftype("struct", nil), -- not yet implemented
  iftype("set", nil), -- not yet implemented
  iftype("bag", nil), -- not yet implemented
  iftype("ToD", U32{"Value"}),
  iftype("date", U32{"Value"}),
  iftype("UTC", U32{"Value"}),
  iftype("clusterId", U16{"Value"}),
  iftype("attribId", U16{"Value"}),
  iftype("bacOID", U32{"Value"}),
  iftype("EUI64", arr{"Value", ashex=true, type=t_U8, length=8}),
  iftype("key128", arr{"Value", ashex=true, type=t_U8, length=16}),
  iftype("unk", nil)
}

msg{"AqaraReport",
  arr {"ReportAttributes",
    U8 {"AttributeIdentifier"},
    msg {ref="Attribute"}
  }
}

end)
